// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dojzsxdzdrdhoisrgpkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvanpzeGR6ZHJkaG9pc3JncGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDMwNjQsImV4cCI6MjA2MDAxOTA2NH0.V9UnyBYnHNhFoDKDRRY7_jquvlqpPW0PxwNsYNmZPIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);